version: 0.2

env:
  variables:
    S3_BUCKET: node-auth-api
    S3_KEY: dist.zip

phases:
  install:
    runtime-versions:
      nodejs: 20
  
  pre_build:
    commands:
      - npm install -g pnpm
      - pnpm install --frozen-lockfile
  
  build:
    commands:
      - pnpm run build
      - pnpm install --prod --ignore-scripts
      - zip -r dist.zip ./dist node_modules
  
  post_build:
    commands:
      - aws s3 cp dist.zip s3://$S3_BUCKET/$S3_KEY
      - aws lambda update-function-code --function-name node-auth-api --s3-bucket $S3_BUCKET --s3-key $S3_KEY
